project_name: finality-provider

builds:
  - id: fpd-linux-amd64
    main: ./finality-provider/cmd/fpd/main.go
    binary: fpd
    hooks:
      pre:
        - wget https://github.com/CosmWasm/wasmvm/releases/download/{{ .Env.COSMWASM_VERSION }}/libwasmvm_muslc.x86_64.a -O /usr/lib/libwasmvm_muslc.x86_64.a
    goos:
      - linux
    goarch:
      - amd64
    env:
      - GO111MODULE=on
    flags:
      - -mod=readonly
      - -trimpath
    tags:
      - netgo
      - osusergo

  - id: eotsd-linux-amd64
    main: ./eotsmanager/cmd/eotsd/main.go
    binary: eotsd
    hooks:
      pre:
        - wget https://github.com/CosmWasm/wasmvm/releases/download/{{ .Env.COSMWASM_VERSION }}/libwasmvm_muslc.x86_64.a -O /usr/lib/libwasmvm_muslc.x86_64.a
    goos:
      - linux
    goarch:
      - amd64
    env:
      - GO111MODULE=on
    flags:
      - -mod=readonly
      - -trimpath
    tags:
      - netgo
      - osusergo

archives:
  - id: zipped
    builds:
      - fpd-linux-amd64
      - eotsd-linux-amd64
    name_template: "{{.ProjectName}}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format: tar.gz
    files:
      - none*
  - id: binaries
    builds:
      - fpd-linux-amd64
      - eotsd-linux-amd64
    name_template: "{{.ProjectName}}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format: binary
    files:
      - none*

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

release:
  github:
    owner: babylonlabs-io
    name: finality-provider

# Docs: https://goreleaser.com/customization/changelog/
changelog:
  disable: true

dist: dist
