name: goreleaser

on:
  push:
    tags:
      - '*'

jobs:
  release:
    uses: babylonlabs-io/.github/.github/workflows/reusable_go_releaser.yml@5d014a155c08d56a1b5673d049f2b4e7d4427825 # v0.19.0 https://github.com/babylonlabs-io/.github/releases/tag/v0.19.0
    secrets: inherit