name: goreleaser

on:
  push:
    tags:
      - '*'

jobs:
  release:
    uses: babylonlabs-io/.github/.github/workflows/reusable_go_releaser.yml@98e4de18638b3d0738c9cbf7e7dfc6e34524db54 # v0.19.1 https://github.com/babylonlabs-io/.github/releases/tag/v0.19.1
    secrets: inherit