name: goreleaser

on:
  push:
    tags:
      - '*'

jobs:
  release:
    uses: babylonlabs-io/.github/.github/workflows/reusable_go_releaser.yml@5151754256060bf160c411d0784f831f29882106 # v0.13.4
    secrets: inherit